import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Add whatever weights you use
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="navbar h-[87px] bg-[#060606] z-10 fixed w-full top-0 left-0 flex justify-around items-center ">
          <h1 className={`text-white ${poppins.className} font-semibold text-[28px]`}>Klavis AI</h1>
          <div className={`flex text-white ${poppins.className} font-medium text-[16px] `}>
            <h1 className="px-[14px]">Home</h1>
            <h1 className="px-[14px]">MCP Server</h1>
            <h1 className="px-[14px]">Eval</h1>
            <h1 className="px-[14px]">Docs</h1>
            <h1 className="px-[14px]">Blog</h1>
            <h1 className="px-[14px]">Pricing</h1>
            <h1 className="px-[14px]">Contact</h1>
          </div>
          <div className="flex items-center">
            <h1 className={`text-white ${poppins.className} font-medium text-[16px] px-[20px]`}>Login</h1>
            <h1 className={`text-white ${poppins.className} font-medium text-[16px] p-[10px] border border-[#ACACAC] rounded-[24px] h-fit`}>Get Started</h1>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
